parameters:
    jonasarts.phpqrcode.class: jonasarts\Bundle\PHPQRCodeBundle\PHPQRCode\PHPQRCode

services:
    phpqrcode:
        class: "%jonasarts.phpqrcode.class%"
        arguments: []
        public: true

    jonasarts\Bundle\PHPQRCodeBundle\PHPQRCode\PHPQRCode: ~